Ex1
YairAmar/Coursera_ML_intro pull request #1
Opened 2021-05-20 11:55 UTC by YairAmar

Exercise 1 is done and ready for a code review

2021-05-20 12:47 UTC, yarinshaked requested changes
Mazal tov, generally pretty good for the first time!

2021-05-20 12:47 UTC, yarinshaked commented on ex1/LinearRegression.py
> +from Utils import *
file_name should be lower case, such as variables, e.g: utils, linear_regression,....

2021-05-20 12:47 UTC, yarinshaked commented on ex1/LinearRegression.py
> +from Utils import *
you should never import *, always specify what you need from the module

2021-05-20 12:47 UTC, yarinshaked commented on ex1/LinearRegression.py
> +        self.theta = np.zeros((2,1))
I suggest you to pass the shape values as an arguments to the constructor

2021-05-20 12:47 UTC, yarinshaked commented on ex1/LinearRegression.py
> +        """
use google docstring format

2021-05-20 12:47 UTC, yarinshaked commented on ex1/LinearRegression.py
> +        self.theta = np.zeros((x.shape[1], 1))
1 seems like a magic number, define it as const in consts.py file

2021-05-20 12:47 UTC, yarinshaked commented on ex1/LinearRegression.py
> +        self.theta = np.zeros((x.shape[1], 1))
why do you define self.theta again?

2021-05-20 12:47 UTC, yarinshaked commented on ex1/LinearRegression.py
> +        """
again use google docstring

2021-05-20 12:47 UTC, yarinshaked commented on ex1/LinearRegression.py
> +        x1 - the input data
it should be the same name as the argument: "x"

2021-05-20 12:47 UTC, yarinshaked commented on ex1/LinearRegression.py
> +        x1 - input data
again should be x

2021-05-20 12:47 UTC, yarinshaked commented on ex1/LinearRegression.py
> +        """
again google docstring

2021-05-20 12:47 UTC, yarinshaked commented on ex1/LinearRegression.py
> +        x1 - input data
again should be x

2021-05-20 12:47 UTC, yarinshaked commented on ex1/Utils.py
> +import numpy as np
I like to import alphabetically but it is your call

2021-05-20 12:47 UTC, yarinshaked commented on ex1/Utils.py
> +    """
again google

2021-05-20 12:47 UTC, yarinshaked commented on ex1/Utils.py
> +    x1 - input data, with a column of 1
again x

2021-05-20 12:47 UTC, yarinshaked commented on ex1/LinearRegression.py
> +            if save_theta:
blank line between if statements

2021-05-20 12:47 UTC, yarinshaked commented on ex1/Utils.py
> +    """
again google

2021-05-20 12:47 UTC, yarinshaked commented on ex1/Utils.py
> +    x1 - input data
again x

2021-05-20 12:47 UTC, yarinshaked commented on ex1/Utils.py
> +    normalize = lambda vec: (vec - np.mean(vec)) / np.std(vec)
you can define an inner function within, instead of lambda expression

2021-05-20 12:47 UTC, yarinshaked commented on ex1/Utils.py
> +    for i in np.arange(x.shape[1] - 1) + 1:
why not use range()?

2021-05-20 12:47 UTC, yarinshaked commented on ex1/Utils.py
> +    """
again google

2021-05-20 12:47 UTC, yarinshaked commented on ex1/Utils.py
> +    x1 - the input data
again x

2021-05-20 12:47 UTC, yarinshaked commented on ex1/Utils.py
> +    """
again google

2021-05-20 12:47 UTC, yarinshaked commented on ex1/Utils.py
> +    x1 - the input data
again x

2021-05-20 12:47 UTC, yarinshaked commented on ex1/Utils.py
> +    theta0s = np.arange(-10, 10, .5)
you can find a better name

2021-05-20 12:47 UTC, yarinshaked commented on ex1/Utils.py
> +    theta1s = np.arange(-1, 8, .5)
same here

2021-05-20 12:47 UTC, yarinshaked commented on ex1/Utils.py
> +    th0, th1, cost = [], [], []
same here

2021-05-20 12:47 UTC, yarinshaked commented on ex1/Utils.py
> +    ax.plot([th[0] for th in theta_hist], [th[1] for th in theta_hist], cost_hist, 'ro-')
it would be more clearer if done outside the function invocation

2021-05-20 12:47 UTC, yarinshaked commented on ex1/Utils.py
> +def plot_cost(doc):
add documentation

2021-05-20 12:47 UTC, yarinshaked commented on ex1/ex1.py
> +if __name__ == "__main__":
main function should be short, encapsulated in a different function

2021-05-20 12:47 UTC, yarinshaked commented on ex1/ex1.py
> +    data_dir1 = "data\ex1data1.txt"
should be command line argument

2021-05-20 12:47 UTC, yarinshaked commented on ex1/ex1.py
> +    data_dir2 = "data\ex1data2.txt"
same here

2021-05-23 07:57 UTC, YairAmar commented on ex1/LinearRegression.py
> +        """
https://www.python.org/dev/peps/pep-0257/
used this, which felt not very comprehensive...
not sure if i did fine

2021-05-23 10:46 UTC, YairAmar commented on ex1/Utils.py
> +    for i in np.arange(x.shape[1] - 1) + 1:
because range returns some sort of an iterable object when i specifically want a list

2021-05-23 11:29 UTC, yarinshaked approved these changes
Mazal Tov, one step closer to not being a noob

2021-05-23 11:30 UTC, merged