Ex2
YairAmar/Coursera_ML_intro pull request #2
Opened 2021-05-26 10:50 UTC by YairAmar

All done, ready for CR

2021-05-27 13:31 UTC, yarinshaked requested changes

2021-05-27 13:31 UTC, yarinshaked commented on ex2/ex2.py
> +def plot_w_regularization(x, y):
type hints

2021-05-27 13:31 UTC, yarinshaked commented on ex2/ex2.py
> +    print("the train accuracy of the linear model is: ", log_reg1.accuracy(x1_train, y1_train))
use fstring formatting

2021-05-27 13:31 UTC, yarinshaked commented on ex2/ex2.py
> +    print("the test accuracy of the linear model is: ", log_reg1.accuracy(x1_test, y1_test))
also fstring

2021-05-27 13:31 UTC, yarinshaked commented on ex2/logistic_regression.py
> +        res = optimize.minimize(cost_function, x0=self.theta, args=(x, y, llambda), method=method,
res is not a good name, maybe result?

2021-05-27 13:31 UTC, yarinshaked commented on ex2/logistic_regression.py
> +        return a prediction over the input data, as a class
Caps

2021-05-27 13:31 UTC, yarinshaked commented on ex2/logistic_regression.py
> +    def accuracy(self, x: np.array, y: np.array) -> float:
bad name, maybe compute_accracy?

2021-05-27 13:31 UTC, yarinshaked commented on ex2/logistic_regression.py
> +        hypo = h(self.theta, x) >= 0.5
predictions might be a better name

2021-05-27 13:31 UTC, yarinshaked commented on ex2/logistic_regression.py
> +        pred = np.array(self.predict(x)) - y
numpy array conversion is not necessary

2021-05-27 13:31 UTC, yarinshaked commented on ex2/utils.py
> +import matplotlib.pyplot as plt
Alphabetic order

2021-05-27 13:31 UTC, yarinshaked commented on ex2/utils.py
> +        z: input array. in the Logistic Regression context should be  theta.T @ x
already hinted at the signature

2021-05-27 13:31 UTC, yarinshaked commented on ex2/utils.py
> +    the
hahaha

2021-05-27 13:31 UTC, yarinshaked commented on ex2/utils.py
> +    data_len = x.shape[0]
be consistent, m or data_len

2021-05-27 13:31 UTC, yarinshaked commented on ex2/utils.py
> +
complete

2021-05-27 13:31 UTC, yarinshaked commented on ex2/utils.py
> +def h(theta: np.array, x: np.array) -> np.array:
bad nameeeeeeeeeeeeee

2021-05-27 13:31 UTC, yarinshaked commented on ex2/utils.py
> +    calculates the cost function with given regularization argument
caps

2021-05-27 13:31 UTC, yarinshaked commented on ex2/utils.py
> +def cost_function(theta: np.array, x: np.array, y: np.array, llambda: float = 0.) -> float:
maybe compute_cost_function

2021-05-30 12:26 UTC, YairAmar commented on ex2/utils.py
> +import matplotlib.pyplot as plt
tbh i prefer it this way - i always put higher the more often-imported packages like numpy, then matplotlib, pandas etc.

2021-05-30 12:26 UTC, YairAmar commented on ex2/utils.py
> +        z: input array. in the Logistic Regression context should be  theta.T @ x
what do you mean? should i remove args?

2021-05-30 12:26 UTC, YairAmar commented on ex2/utils.py
> +    the
:( 
ikr

2021-05-31 12:55 UTC, yarinshaked requested changes

2021-05-31 12:55 UTC, yarinshaked commented on ex1/utils.py
> +    for i in np.arange(x.shape[1] - 1) + 1:
you can use range(1, x.shape[1])

2021-05-31 12:55 UTC, yarinshaked commented on ex2/ex2.py
> +    poly_reg = PolynomialFeatures(6)
Single Responsibility! this function should only get the values it need for the plot and plot them

2021-05-31 12:55 UTC, yarinshaked commented on ex2/ex2.py
> +    llambdas = [0., 1., 10., 100.]
name is not clear

2021-05-31 12:55 UTC, yarinshaked commented on ex2/ex2.py
> +    plt.grid()
same

2021-05-31 12:55 UTC, yarinshaked commented on ex2/ex2.py
> +    poly = PolynomialFeatures(1)
extract to preprocess function

2021-05-31 12:55 UTC, yarinshaked commented on ex2/logistic_regression.py
> +
document class purpose

2021-05-31 12:55 UTC, yarinshaked commented on ex2/logistic_regression.py
> +        The constructor of the LogisticRegression object
dot at EOL

2021-05-31 12:55 UTC, yarinshaked commented on ex2/logistic_regression.py
> +        Trains the logistic regression model
same

2021-05-31 12:55 UTC, yarinshaked commented on ex2/logistic_regression.py
> +        self.poly = PolynomialFeatures(deg)
you can send it as an argument, it was created at the main function

2021-05-31 12:55 UTC, yarinshaked commented on ex2/logistic_regression.py
> +        predictions = compute_hypothesis(self.theta, x) >= 0.5
set as const (in general should be inside a .yml configuration file but const if enough for now(: )

2021-05-31 12:55 UTC, yarinshaked commented on ex2/logistic_regression.py
> +        Calculates the accuracy of the classifier
same

2021-05-31 12:55 UTC, yarinshaked commented on ex2/logistic_regression.py
> +        pred = self.predict(x) - y
use == instead

2021-05-31 12:55 UTC, yarinshaked commented on ex2/utils.py
> +    Loading data and formatting for the latter linear regression
same

2021-05-31 12:55 UTC, yarinshaked commented on ex2/utils.py
> +        z: input array. in the Logistic Regression context should be  theta.T @ x
you already hinted

2021-05-31 12:55 UTC, yarinshaked commented on ex2/utils.py
> +    Splits the data into 2 groups - train and test, in a proportion given by ratio
same

2021-05-31 12:55 UTC, yarinshaked commented on ex2/utils.py
> +    Applies a sigmoid function over the input
same

2021-05-31 12:55 UTC, yarinshaked commented on ex2/utils.py
> +    Plots all values of the cost-function acquired through the training of the model
same

2021-05-31 12:55 UTC, yarinshaked commented on ex2/utils.py
> +    Computes the hypothesis function
same

2021-05-31 12:55 UTC, yarinshaked commented on ex2/utils.py
> +    Calculates the cost function with given regularization argument
same

2021-06-01 09:07 UTC, YairAmar commented on ex2/utils.py
> +        z: input array. in the Logistic Regression context should be  theta.T @ x
fixed

2021-06-01 09:11 UTC, YairAmar commented on ex1/utils.py
> +    for i in np.arange(x.shape[1] - 1) + 1:
done

2021-06-01 09:14 UTC, YairAmar commented on ex2/ex2.py
> +    llambdas = [0., 1., 10., 100.]
fixed -> lambda_values

2021-06-01 09:17 UTC, YairAmar commented on ex2/ex2.py
> +    plt.grid()
done

2021-06-01 10:27 UTC, YairAmar commented on ex2/ex2.py
> +    poly = PolynomialFeatures(1)
done

2021-06-01 10:35 UTC, YairAmar commented on ex2/utils.py
> +    Splits the data into 2 groups - train and test, in a proportion given by ratio
done

2021-06-01 10:51 UTC, YairAmar commented on ex2/logistic_regression.py
> +
done

2021-06-01 11:10 UTC, YairAmar commented on ex2/logistic_regression.py
> +        The constructor of the LogisticRegression object
done

2021-06-01 11:10 UTC, YairAmar commented on ex2/logistic_regression.py
> +        Trains the logistic regression model
done

2021-06-01 11:29 UTC, YairAmar commented on ex2/logistic_regression.py
> +        predictions = compute_hypothesis(self.theta, x) >= 0.5
named the constant THRESHOLD

2021-06-01 11:29 UTC, YairAmar commented on ex2/logistic_regression.py
> +        Calculates the accuracy of the classifier
done

2021-06-01 11:30 UTC, YairAmar commented on ex2/logistic_regression.py
> +        pred = self.predict(x) - y
done

2021-06-01 11:30 UTC, YairAmar commented on ex2/utils.py
> +    Loading data and formatting for the latter linear regression
fixed

2021-06-01 11:30 UTC, YairAmar commented on ex2/utils.py
> +    Plots all values of the cost-function acquired through the training of the model
fixed

2021-06-01 11:30 UTC, YairAmar commented on ex2/utils.py
> +    Computes the hypothesis function
fixed

2021-06-01 11:31 UTC, YairAmar commented on ex2/utils.py
> +    Applies a sigmoid function over the input
done

2021-06-01 11:31 UTC, YairAmar commented on ex2/logistic_regression.py
> +        self.poly = PolynomialFeatures(deg)
cant do since PolynomialFeatures is now used from within the preprocessing method

2021-06-01 11:34 UTC, YairAmar commented on ex2/ex2.py
> +    poly_reg = PolynomialFeatures(6)
have to train the models in order to plot the decision boundaries anyways.

2021-06-03 13:27 UTC, merged